#define spinix_heapstart_min      0x6000
#define spinix_heapstart0         0x7d00
#define spinix_heapafter          0x7de0
#define spinix_proc_table         0x7de0
#define spinix_environ_vars       0x7e50
#define spinix_environ_vars_end   0x7ed3
#define spinix_argv_parms         0x7ed4
#define spinix_return_value       0x7f84
#define spinix_config             0x7f88
#define spinix_scriptline         0x7f8c
#define spinix_ifflag             0x7f90
#define spinix_whileflag          0x7f94
#define spinix_shell_level        0x7f98
#define spinix_bootflag           0x7f9c
#define spinix_shell_sector       0x7fa0
#define spinix_shell_size         0x7fa4
#define spinix_stdin              0x7fa8
#define spinix_stdin_handle       0x7fac
#define spinix_stdout             0x7fb0
#define spinix_stdout_handle      0x7fb4
#define spinix_serial_cog         0x7fb8
#define spinix_serial_handle      0x7fbc
#define spinix_keyboard_cog       0x7fc0
#define spinix_keyboard_handle    0x7fc4
#define spinix_vga_cog            0x7fc8
#define spinix_vga_handle         0x7fcc
#define spinix_sd_pins            0x7fd0
#define spinix_spi_engine_cog     0x7fd4
#define spinix_spi_command        0x7fd8
#define spinix_spi_block_index    0x7fdc
#define spinix_spi_buffer_address 0x7fe0
#define spinix_unixtime           0x7fe4
#define spinix_cycle0             0x7fe8
#define spinix_timezone           0x7fec
#define spinix_memlocknum         0x7ff0
#define spinix_memfreelist        0x7ff4
#define spinix_malloclist         0x7ff8
#define spinix_heapstart          0x7ffc
#define spinix_checkword          0xdead1eaf
#define spinix_proc_type_spin     1
#define spinix_proc_type_pasm     2
#define spinix_proc_type_capp     3
#define spinix_proc_type_driver   0x80
#define spinix_run_shell_wait     0x00
#define spinix_run_shell_nowait   0x08
#define spinix_run_kill_caller    0x10
#define spinix_run_at_address0    0x20
#define spinix_run_c_program      0x40
#define spinix_run_spin_program   0x80
#define spinix_run_stand_alone    0x100

void spinix_enter(void);
void spinix_exit(int retval);
